### ISSUE TITLE
Gull sometimes causes crash

### ISSUE THREAD

**Issue by AyyMang** [aqariio/Fowl-Play#25] opened 2024-11-27 22:29 UTC
One of my worlds is consistently crashing shortly after load with a `java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage` error on the gull entity. 

`java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage
	at knot//net.minecraft.class_5132.method_26865(class_5132.java:22)
	at knot//net.minecraft.class_5132.method_26862(class_5132.java:28)
	at knot//net.minecraft.class_5131.method_26852(class_5131.java:76)
	at knot//net.minecraft.class_1309.method_26825(class_1309.java:1904)
	at knot//net.minecraft.class_1308.method_6121(class_1308.java:1437)
	at knot//net.minecraft.class_4816.method_46990(class_4816.java:27)
	at knot//net.minecraft.class_7898$1.trigger(class_7898.java:53)
	at knot//net.minecraft.class_7894.method_18922(class_7894.java:20)
	at knot//net.minecraft.class_4095.method_18891(class_4095.java:736)
	at knot//net.minecraft.class_4095.method_19542(class_4095.java:492)
	at knot//aqario.fowlplay.common.entity.GullEntity.method_5958(GullEntity.java:246)
	at knot//net.minecraft.class_1308.method_6023(class_1308.java:788)
	at knot//net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at knot//net.minecraft.class_1308.method_6007(class_1308.java:550)
	at knot//net.minecraft.class_1296.method_6007(class_1296.java:128)
	at knot//net.minecraft.class_1429.method_6007(class_1429.java:58)
	at knot//aqario.fowlplay.common.entity.BirdEntity.method_6007(BirdEntity.java:103)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:351)
	at knot//aqario.fowlplay.common.entity.FlyingBirdEntity.method_5773(FlyingBirdEntity.java:86)
	at knot//aqario.fowlplay.common.entity.GullEntity.method_5773(GullEntity.java:180)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.wrapOperation$gel000$sleepingoverhaul$onCallTickServer(MinecraftServer.java:9825)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by aqariio** [comment] 2024-11-27 22:31
If I am correct in assuming that this is in 1.20.1, then the issue is fixed in the newest update, 1.0.0-beta.2+1.20.1

**Closed** 2024-11-27 23:02 UTC
Labels: duplicate
